spring.application.name=payment_api_service

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/Payment
spring.datasource.username=postgres
spring.datasource.password=firstproject

spring.jpa.hibernate.ddl-auto=create

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
